CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'USERNAME'@'%' IDENTIFIED BY 'MYPASSWORD';
GRANT ALL ON wordpress.* TO 'USERNAME'@'%';

ALTER USER 'root'@'localhost' IDENTIFIED BY 'ROOTPASSWORD';
GRANT ALL ON *.* TO 'root'@'localhost';
FLUSH PRIVILEGES;